title: "Selbsteinschätzung der Qualität in Zürcher KITAs"

header_links:
  - label: "Datenschutz"
    url: "https://www.zhaw.ch/de/datenschutz/"
  - label: "Rechtliche Hinweise"
    url: "https://www.zhaw.ch/de/rechtliche-hinweise/"

legal_notice:
  institution: "ZHAW Zürcher Hochschule für Angewandte Wissenschaften"
  unit:
    label: "Qualitätsfachstelle für Zürcher Kitas"       # leave blank to hide
    link_text: "ZHAW Website der Qualitätsfachstelle"   # optional: display text for the link
    link_url: "https://www.zhaw.ch/de/sozialearbeit/qualitaet-in-zuercher-kitas"    # optional: URL for the link
  department: "Departement Soziale Arbeit"
  institute: "Institut für Kindheit, Jugend und Familie"
  contact: "Kontakt: kita.fachstelle@zhaw.ch"
