title: "SELE – Selbsteinschätzung der Qualität in Zürcher KITAs"

brand: "black" # options are: standard | black

legal_notice:
  - "ZHAW Zürcher Hochschule für Angewandte Wissenschaften"
  - "Soziale Arbeit"
  - "Institut für Kindheit, Jugend und Familie"
  - "Contact"
